In [ ]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install sklearn
!pip install keras

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression


In [52]:
dataset = pd.read_csv('housesprices.csv',names=['serial','year','age','distance','stores','latitude','longitude','price'])

In [ ]:
dataset.info()

In [54]:
dataset = dataset.drop(["serial"],axis=1);
dataset.head()

year  age  distance  stores  latitude  longitude  price
0  2009   21         9       6        84        121  14264
1  2007    4         2       3        86        121  12032
2  2016   18         3       7        90        120  13560
3  2002   13         2       2        80        128  12029
4  2014   25         5       8        81        122  14157

In [55]:
X = dataset.drop('price',axis=1); # creiamo l'array numpy delle features droppando dal dataset l'ultima colonna che contiene le labels
Y = dataset['price'].values; # creiamo l'array numpy prendendo dal dataset solamente la colonna che contiene le labels

In [ ]:
sc = StandardScaler()
X_scaled = sc.fit_transform(X)
X_scaled

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.1)


In [58]:
model = LinearRegression()
history = model.fit(X_train, Y_train)

In [59]:
Y_pred = model.predict(X_test)
Y_pred

array([12667.12298444, 13251.02076915, 15933.74575843, 14965.4430218 ,
       15328.10064231, 12315.88863908, 14420.74537984, 14623.42814358,
       15076.08547046, 14007.25150875, 13818.91481046, 12626.03790948,
       14105.78427771, 15089.65208915, 15032.09100037, 13486.21167245,
       14117.55075143, 13688.60089386, 14233.05423654, 13674.49046418,
       14139.19196908, 15060.08569077, 14209.34693054, 15718.5685865 ,
       14037.72555406, 13599.37924269, 13120.74166598, 14140.31137933,
       13231.57866919, 14782.50922255, 12415.72812352, 13850.88113731,
       13875.56401766, 12777.49982483, 14810.33086601, 14202.0513716 ,
       12132.26546239, 14257.68638993, 14562.69425663, 15534.1373562 ,
       12663.79221589, 13408.10981015, 13962.00282419, 14847.89281496,
       13201.37437765, 12679.10949424, 15271.11456294, 13302.65314264,
       14374.31005693, 14394.17115467, 14306.9387083 , 12393.66008618,
       15502.35553973, 13611.11908172, 13800.9532152 , 15647.75185968,
      

In [60]:
Y_test

array([12121, 14095, 15876, 15224, 14671, 12785, 15042, 14271, 15224,
       14546, 14270, 12583, 14606, 14314, 15103, 14292, 13958, 14184,
       14212, 13928, 14585, 15055, 13884, 15783, 14178, 13295, 13381,
       13986, 12840, 15048, 12164, 13487, 14717, 12913, 15643, 14473,
       11788, 14154, 14995, 15449, 13186, 13239, 13408, 15375, 12716,
       13306, 15382, 13071, 13979, 14651, 14111, 12204, 16168, 13979,
       14025, 16045, 13923, 15571, 13901, 15777, 14688, 12465, 14142,
       14590, 14994, 14559, 14056, 13531, 13547, 12509, 14169, 13324,
       14927, 13050, 12498, 13966, 13488, 15479, 14844, 15124, 13722,
       12827, 15091, 13511, 15687, 14702, 12358, 12327, 13432, 13817,
       12869, 14047, 13330, 13577, 13439, 13493, 14915, 12619, 14041,
       15184, 12295, 14415, 12133, 15829, 14646, 13372, 12365, 12573,
       12415, 13309, 13771, 15861, 11988, 14279, 15739, 13293, 14866,
       13356, 14404, 14884, 13568, 16358, 14069, 14280, 13012, 13159,
       13145, 14643,

facciamo adesso una prova creando noi un nostro personale array di valori per ognuna delle features e ottenendo cosi' il prezzo predetto. Possiamo controllare che si avvicini ai valori del dataset su dati simili a quelli che insieriamo

In [62]:
valori_test = np.array([[2016,	18,	3,	7, 90, 120]],dtype=np.int32) #creiamo l'array numpy dei valori per i quali vogliamo effettuare la predizione
valori_test_transformed = sc.transform(valori_test) #effettuiamo lo scale di questi valori utilizzando lo stesso scaler usato in addestramento
Y_vtp = model.predict(valori_test_transformed) #effettuiamo la predizione
Y_vtp # mostriamo i valori ottenuti

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([13554.5764315])